apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
      nodePort: 31000  # Choose a port between 30000-32767
  type: NodePort
